# Stage 0 - Build
FROM node:11-alpine as build

ARG REACT_APP_RUNTIME
ENV REACT_APP_RUNTIME=$REACT_APP_RUNTIME

WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY ./ /app/

RUN npm run build

# Stage 1 - Serve
FROM nginx:alpine

COPY --from=build /app/build/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
