apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hub
  namespace: fushigi
  labels:
    app: fushigi
    run: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fushigi
      run: hub
  template:
    metadata:
      labels:
        app: fushigi
        run: hub
    spec:
      containers:
      - image: kurai/fushigi/hub
        name: hub
