apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scheduler
  namespace: fushigi
  labels:
    app: fushigi
    run: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fushigi
      run: scheduler
  template:
    metadata:
      labels:
        app: fushigi
        run: scheduler
    spec:
      serviceAccountName: scheduler-sa
      containers:
      - image: kurai/fushigi/scheduler
        name: scheduler
