apiVersion: skaffold/v1beta7
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
  artifacts:
  - image: kurai/fushigi/hub
    context: ./hub/
    sync:
      '*.js': .

  - image: kurai/fushigi/scheduler
    context: ./scheduler/
    sync:
      '*.js': .

  - image: kurai/fushigi/client
    context: ./client/
    sync:
      '*.js': .

  - image: kurai/fushigi/runner
    context: ./runner/
    sync:
      '*.js': .
deploy:
  kubectl:
    manifests:
    - ./deploy/kubernetes/*
