apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: kurai/fushigi/hub
    context: ./hub/
    sync:
      '*.js': .

  - image: kurai/fushigi/scheduler
    context: ./scheduler/
    sync:
      '*.js': .

  - image: kurai/fushigi/runner
    context: ./runner/
    sync:
      '*.js': .
deploy:
  kubectl:
    manifests:
    - ./deploy/kubernetes/*
