apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: fushigi
  labels:
    app: fushigi
    run: client
spec:
  type: ClusterIP
  selector:
    app: fushigi
    run: client
  ports:
  - name: http
    port: 3000
    targetPort: 3000
