apiVersion: v1
kind: Service
metadata:
  labels:
    app: fushigi
    run: controller
  name: controller
spec:
  type: ClusterIP
  selector:
    app: fushigi
    run: controller
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
