apiVersion: v1
kind: Service
metadata:
  name: hub
  namespace: fushigi
  labels:
    app: fushigi
    run: hub
spec:
  type: ClusterIP
  selector:
    app: fushigi
    run: hub
  ports:
  - name: ws
    port: 3000
    targetPort: 3000
