apiVersion: v1
kind: Service
metadata:
  labels:
    app: fushigi
    run: scheduler
  name: scheduler
spec:
  type: ClusterIP
  selector:
    app: fushigi
    run: scheduler
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
