apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: fushigi
  labels:
    app: fushigi
    run: scheduler
spec:
  type: ClusterIP
  selector:
    app: fushigi
    run: scheduler
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
