apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: runner
  namespace: fushigi
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - headers:
        runner:
          exact: PUT_RUNNER_ID_HERE
    route:
    - destination:
        host: runner
