apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-sa
  namespace: fushigi
  labels:
    app: fushigi
    run: scheduler
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: fushigi
  name: scheduler-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduler-rb
  namespace: fushigi
  labels:
    app: fushigi
    run: scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduler-role
subjects:
- kind: ServiceAccount
  name: scheduler-sa
  namespace: fushigi
