apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: scheduler
  namespace: fushigi
spec:
  hosts:
  - scheduler
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: scheduler
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: fushigi
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
